gh-actions: improve error message when compiled css was not commited

diff --git a/.github/workflows/rexlint.yml b/.github/workflows/rexlint.yml
--- a/.github/workflows/rexlint.yml
+++ b/.github/workflows/rexlint.yml
@@ -43,5 +43,12 @@ jobs:
             - run: |
                   vendor/bin/rexlint
                   php redaxo/bin/console be_style:compile --ansi
-                  git checkout -- redaxo/src/core/default.config.yml # revert changes made initially
-                  git diff HEAD --exit-code # check if compiling the scss lead to uncommitted changes
+
+                  # revert changes made initially
+                  git checkout -- redaxo/src/core/default.config.yml
+
+                  # check if compiling the scss lead to uncommitted changes
+                  git diff HEAD --exit-code --output=/dev/null
+                  if [ "$?" -ne 0 ] then
+                    echo "::error it seems you missed to commit the compiled css files"
+                  fi
