Composer-Scripts optimiert/ergänzt + Tools-Update

diff --git a/.github/workflows/static-analysis.yml b/.github/workflows/static-analysis.yml
--- a/.github/workflows/static-analysis.yml
+++ b/.github/workflows/static-analysis.yml
@@ -70,7 +70,7 @@ jobs:
                 id: baseline
                 run: |
                     vendor/bin/psalm --set-baseline=.tools/psalm/baseline.xml --stats
-                    git diff --exit-code .tools/psalm/baseline.xml || (echo "::error file=.tools/psalm/baseline.xml,line=1,col=1::Psalm baseline file is outdated and must be regenerated via \`composer psalm-baseline\`." && exit 1)
+                    git diff --exit-code .tools/psalm/baseline.xml || (echo "::error file=.tools/psalm/baseline.xml,line=1,col=1::Psalm baseline file is outdated and must be regenerated via \`composer psalm:baseline\`." && exit 1)
 
             -   name: Git pull
                 if: failure() && steps.baseline.conclusion != 'skipped' && github.event_name == 'repository_dispatch'
@@ -139,8 +139,8 @@ jobs:
             -   name: Check psalm baseline
                 id: baseline
                 run: |
-                    composer taint-baseline
-                    git diff --exit-code .tools/psalm/baseline-taint.xml || (echo "::error file=.tools/psalm/baseline-taint.xml,line=1,col=1::Psalm taint baseline file is outdated and must be regenerated via \`composer taint-baseline\`." && exit 1)
+                    composer taint:baseline
+                    git diff --exit-code .tools/psalm/baseline-taint.xml || (echo "::error file=.tools/psalm/baseline-taint.xml,line=1,col=1::Psalm taint baseline file is outdated and must be regenerated via \`composer taint:baseline\`." && exit 1)
 
             -   name: Git pull
                 if: failure() && steps.baseline.conclusion != 'skipped' && github.event_name == 'repository_dispatch'
@@ -212,8 +212,8 @@ jobs:
                 if: github.event_name == 'repository_dispatch'
                 id: baseline
                 run: |
-                    composer phpstan-baseline
-                    git diff --exit-code .tools/phpstan/baseline.neon || (echo "::error file=.tools/psalm/baseline-taint.xml,line=1,col=1::PHPStan baseline file is outdated and must be regenerated via \`composer phpstan-baseline\`." && exit 1)
+                    composer phpstan:baseline
+                    git diff --exit-code .tools/phpstan/baseline.neon || (echo "::error file=.tools/phpstan/baseline.neon,line=1,col=1::PHPStan baseline file is outdated and must be regenerated via \`composer phpstan:baseline\`." && exit 1)
 
             -   name: Git pull
                 if: failure() && steps.baseline.conclusion != 'skipped' && github.event_name == 'repository_dispatch'
